language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-hero' ]; then cd .. && eval "mv $currentfolder generator-hero" && cd generator-hero; fi

